### ISSUE TITLE
Fixup Chococolatey moderation requirements

### ISSUE THREAD

**Issue by AndyCross** [elastacloud/parq#12]
```
* please remove the calls to Set-Location and to Add-Type (neither of those are needed).
* Also the next time, please remove the admin tag.
* Instead of linking to a markdown file in the package description, please add the the content directly in the description (or at least part of the content).
```

**Comment by AdmiringWorm** [comment]
I should have been clearer. Only the second item is actually required to be fixed the next time, the other two was meant as **strong** suggestions.

Would be nice if it was possible to fix the other two guidelines that the automated `chocolatey-ops` user mentioned as well:

- The iconUrl should be added if there is one. Please correct this in the nuspec, if applicable. [More...](https://github.com/chocolatey/package-validator/wiki/IconUrlMissing)
- Release Notes (releaseNotes) are a short description of changes in each version of a package. Please include releasenotes in the nuspec. NOTE: To prevent the need to continually update this field, providing a URL to an external list of Release Notes is perfectly acceptable. [More...](https://github.com/chocolatey/package-validator/wiki/ReleaseNotesNotEmpty)

*Guidelines are usually considered something to fix for next time to increase the quality of the package.*

**Comment by AdmiringWorm** [comment]
Of course, those are only valid if you actually provide them for the software itself.

**Comment by AndyCross** [comment]
We don't have an icon! I'll create a separate issue for that and then the iconUrl can be added.

WRT to release notes we also need to track those better and I'll create a list of things new in each release from now on. 

See https://chocolatey.org/packages/parq/2.0.0.0 which contains changes in https://github.com/elastacloud/parq/commit/f897853c456ccf94a668de4c8921c257ac65b525

**Comment by AndyCross** [comment]
Note that v3 onwards will have an icon, due to the way we're running milestones currently there will be a local choco package that isn't submitted for validation until the milestone gets closed. pM2 is in choco as 2.0.0.0, pM3 will make choco as v3.0.0.0. Any bugs raised against pM2 or pM3 will become pMn.x.y.z as required by the hotfix process.
